export const static_result = {
  sip: [
    {
      dt_created: '28/08/2020',
      sip_only: true,
      is_sip: true,
      exit_load: null,
      all_units: false,
      name: 'SIP',
      status: 'active',
      folio_wise: [
        {
          units: null,
          amount: null,
          folio_number: '',
          all_units: null,
        },
        {
          units: null,
          amount: null,
          folio_number: '',
          all_units: null,
        },
      ],
      remarks: 'Testing campaign2',
      folio_number: '',
      amount: 1000,
      recommended_mf: {
        curr_nav: 1000.0,
        friendly_name: 'Mirae Asset Cash Management Fund',
        isin: 'INF769K01CM1',
        nav_date: '12/15/2016',
        name: 'MIRAE ASSET CASH MANAGEMENT FUND - DIRECT PLAN - GROWTH',
        amfi: 'INF769K01CM1',
        amc: null,
        bond_stock: null,
        amc_logo_big: 'http://localhost/static/img/amc-logo/high-res/mirae_asset.png',
        amc_logo_small: 'http://localhost/static/img/amc-logo/low-res/mirae_asset.png',
        mfid: 'INF769K01CM1',
      },
      units: null,
      mf: {
        curr_nav: 10.0,
        friendly_name: 'Icici Prudential Bluechip Fund',
        isin: 'INF109K01BL4',
        nav_date: '07/19/2010',
        name: 'ICICI PRUDENTIAL BLUECHIP FUND - GROWTH',
        amfi: 'INF109K01BL4',
        amc: null,
        bond_stock: null,
        amc_logo_big: 'http://localhost/static/img/amc-logo/high-res/icici_new.png',
        amc_logo_small: 'http://localhost/static/img/amc-logo/low-res/icici_new.png',
        mfid: 'INF109K01BL4',
      },
      allowed_sip_dates: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      default_sip_date: '2nd',
    },
  ],
};
