image:
  name: node:12.20.0

definitions:
  caches:
    image: node

  steps:
    - step: &pod-deploy
        name: Pipeline-on-demand deploy steps
        script:
          - apt-get update
          - npm config set strict-ssl false;
          - cd react_webviews
          - npm install
          - npm run build &
          - sleep 60
          - ls
          - mv build $BITBUCKET_COMMIT
          - pipe: atlassian/google-cloud-storage-deploy:0.4.5
            variables:
              KEY_FILE: $KEY_FILE
              PROJECT: 'plutus-admin'
              BUCKET: 'plutus-webview'
              SOURCE: '$BITBUCKET_COMMIT'

pipelines:
  custom:
    pod-deploy:
      - step:
          <<: *pod-deploy
          name: Pipeline-on-demand deploy
