export const allocations = [
  { sector: 'Bank', allocation: 29 },
  { sector: 'Refineries/marketing', allocation: 17 },
  { sector: 'Computers-software', allocation: 11 },
  { sector: 'Engineering, designing, construction', allocation: 10 },
  { sector: 'Housing finance', allocation: 8 },
];

export const topStocks = [
  { heading: 'Computer-Software', company: 'Infosys Ltd', percentage: 10.06 },
  { heading: 'Banks', company: 'HDFC Bank Ltd.', percentage: 9.12 },
  {
    heading: 'Refineries/Marketing',
    company: 'Reliance Industries Ltd',
    percentage: 9.12,
  },
  {
    heading: 'Computer - Software',
    company: 'Tata Consultancy Ltd.',
    percentage: 10.06,
  },
  { heading: 'NBFC', company: 'Bajaj Finance Ltd', percentage: 9.12 },
  { heading: 'Banks', company: 'Kotak Mahindra Bank Ltd.', percentage: 10.06 },
  { heading: 'Computer-Software', company: 'Infosys Ltd', percentage: 10.06 },
  { heading: 'Banks', company: 'HDFC Bank Ltd.', percentage: 9.12 },
  {
    heading: 'Refineries/Marketing',
    company: 'Reliance Industries Ltd',
    percentage: 9.12,
  },
  {
    heading: 'Computer - Software',
    company: 'Tata Consultancy Ltd.',
    percentage: 10.06,
  },
  { heading: 'NBFC', company: 'Bajaj Finance Ltd', percentage: 9.12 },
  { heading: 'Banks', company: 'Kotak Mahindra Bank Ltd.', percentage: 10.06 },
  { heading: 'Computer-Software', company: 'Infosys Ltd', percentage: 10.06 },
  { heading: 'Banks', company: 'HDFC Bank Ltd.', percentage: 9.12 },
  {
    heading: 'Refineries/Marketing',
    company: 'Reliance Industries Ltd',
    percentage: 9.12,
  },
  {
    heading: 'Computer - Software',
    company: 'Tata Consultancy Ltd.',
    percentage: 10.06,
  },
  { heading: 'NBFC', company: 'Bajaj Finance Ltd', percentage: 9.12 },
  { heading: 'Banks', company: 'Kotak Mahindra Bank Ltd.', percentage: 10.06 },
];

export const topAMCs = [
  { name: 'SBI Mutual Fund', percentage: 8 },
  { name: 'L & T Mutual Fund', percentage: 18 },
  { name: 'Aditya Birla Capital', percentage: 9 },
  { name: 'Axis Mutual Fund', percentage: 8 },
  { name: 'Kotak Mututal Fund', percentage: 7 },
  { name: 'ICICI Prudential Asset Management', percentage: 7 },
  { name: 'BNP Paribas', percentage: 5 },
  { name: 'Invesco Asset Management', percentage: 3 },
  { name: 'Pnb Asset Management Company', percentage: 3 },
  { name: 'Hdfc Asset Management', percentage: 5 },
  { name: 'SBI Mutual Fund', percentage: 8 },
  { name: 'L & T Mutual Fund', percentage: 18 },
  { name: 'Aditya Birla Capital', percentage: 9 },
  { name: 'Axis Mutual Fund', percentage: 8 },
  { name: 'Kotak Mututal Fund', percentage: 7 },
  { name: 'ICICI Prudential Asset Management', percentage: 7 },
  { name: 'BNP Paribas', percentage: 5 },
  { name: 'Invesco Asset Management', percentage: 3 },
  { name: 'Pnb Asset Management Company', percentage: 3 },
  { name: 'Hdfc Asset Management', percentage: 5 },
  { name: 'SBI Mutual Fund', percentage: 8 },
  { name: 'L & T Mutual Fund', percentage: 18 },
  { name: 'Aditya Birla Capital', percentage: 9 },
  { name: 'Axis Mutual Fund', percentage: 8 },
  { name: 'Kotak Mututal Fund', percentage: 7 },
  { name: 'ICICI Prudential Asset Management', percentage: 7 },
  { name: 'BNP Paribas', percentage: 5 },
  { name: 'Invesco Asset Management', percentage: 3 },
  { name: 'Pnb Asset Management Company', percentage: 3 },
  { name: 'Hdfc Asset Management', percentage: 5 },
];

export const topHoldings = [
  { name: 'GOI', percentage: 15.92 },
  { name: 'Rural Electrification Corpn. Ltd.', percentage: 6.21 },
  { name: 'Housing Development Finance Corpn. Ltd.', percentage: 5.4 },
  { name: 'State Bank of India', percentage: 4.87 },
  { name: 'Vedanta Ltd.', percentage: 2.74 },
  { name: 'IndInfravit Trust', percentage: 2.61 },
  { name: 'Mahanagar Telephone Nigam Ltd.', percentage: 2.38 },
  { name: 'Housing & Urban Development Corpn. Ltd.', percentage: 2.2 },
  { name: 'GOI', percentage: 15.92 },
  { name: 'Rural Electrification Corpn. Ltd.', percentage: 6.21 },
  { name: 'Housing Development Finance Corpn. Ltd.', percentage: 5.4 },
  { name: 'State Bank of India', percentage: 4.87 },
  { name: 'Vedanta Ltd.', percentage: 2.74 },
  { name: 'IndInfravit Trust', percentage: 2.61 },
  { name: 'Mahanagar Telephone Nigam Ltd.', percentage: 2.38 },
  { name: 'Housing & Urban Development Corpn. Ltd.', percentage: 2.2 },
];

export const genericErrMsg = 'Oops, something went wrong please try again after sometime';