export const apiConstants = {
  reportSummaryV2:
    "/api/invest/reportv4/portfolio/summary/v2?upcoming_needed=y",
  reportGoals: "/api/invest/reportv4/portfolio/summary?upcoming_needed=y",
  getFunds: "/api/invest/reportv4/portfolio/funds",
  getFundMf: "/api/mf/v2",
  getFundDetailsForSwitch: "/api/invest/reportv4/portfolio/fund-detail",
  getTransactions: "/api/invest/transactionv4",
  getFundsWiseTransactions: "/api/invest/transactionv4",
};

export const getPathname = {
  invest: "/invest",
  buildwealth: "/invest/buildwealth",
  savetax: "/invest/savetax",
  investGold: "/invest/advanced-investing/gold",
  reliancesmartsaveBreakUp: "/invest/reliancesmartsave/breakup",
  parkmoney: "/invest/parkmoney",
  savegoal: "/invest/savegoal/",
  monthlyincomeplan: "/invest/advanced-investing/monthlyincomeplan",
  midcap: "/invest/advanced-investing/midcap",
  arbitrage: "/invest/advanced-investing/arbitrage",
  advancedInvestingIndex: "/invest/advanced-investing/index",
  shariah: "/invest/advanced-investing/shariah",
  balanced: "/invest/advanced-investing/balanced",
  legacy: "/import/folio",
  sectoral: "/invest/advanced-investing/sectoral",
  explore: "/invest/explore",
  instaredeem: "/invest/instaredeem",
  npsInvestments: "/nps/investents",
  withdraw: "/withdraw",
  withdrawReason: "/withdraw-reason/",
  reportGoals: "/reports/goals",
  reportsPurchased: "/reports/purchased-transaction",
  reportsRedeemed: "/reports/redeemed-transaction",
  reportsSwitched: "/reports/switched-transaction",
  reportsSip: "/reports/sip",
  reportsTransactions: "/reports/transactions",
  reportsFundswiseSummary: "/reports/fundswise/summary",
  reportsFunds: "/reports/goals/funds/",
  reportsFundswiseSwitch: "/reports/fundswise/switch/",
  reportsFundswiseTransactions: "/reports/transactions/",
  reportsFundswiseDetails: "/reports/fundswise/details/",
};

export const storageConstants = {
  USER: "user",
  KYC: "kyc",
  PENDING_PURCHASE: "pending_purchase",
  PENDING_REDEMPTION: "pending_redemption",
  SIPS: "sips",
};
